name: Post-Merge Messages
on:
  pull_request_target:
    types: [synchronize, closed]
  issues:
    types: [closed]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Get Changed Files
        id: changed_files
        uses: actions/checkout@v3

      - name: Print Changed Files
        run: |
          CHANGED_FILES="${{ steps.changed_files.outputs.all_changed_files }}"
          echo "Changed files: $CHANGED_FILES"

      - name: Post Message
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesClosed: |
            Thanks for closing this Issue!
            Please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs, or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
          pullRequestMerged: |
            👋 @{{ author }}
            You have contributed to Codecademy Docs, and we would like to know more about you and your experience.
            Please take a minute to fill out [this four question survey](https://codecademyready.typeform.com/to/O3hzYoBB) to help us better understand Docs contributions and how we can improve the experience for you and our learners.
            Thank you for your help!

            🎉 Your contributions can be seen here:
            
            ${}
            
            Please note it may take a little while for changes to become visible.
            It looks as if you're anonymous. If you want to be credited, see [My contribution is live but I’m not being shown as a contributor, why is this?](https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036)
